### PR TITLE
Meet new PayU unit price requirement

### PR DESCRIPTION
**Pull request by Szpakusik**

### CODE REVIEW

**Comment by WilczekCK** [comment]
Some link about what is it? 🤔

**Comment by WilczekCK** [comment]
Is it completed? 👍

**Comment by Szpakusik** [comment]
Yeah, Payu API either got more restrictive lastly or there is some deeper issue in data flow. 
The API requires unit price as the integer of cents. 

HotFix already in production. Plus sign might be unnecessary.

**Comment by WilczekCK** [comment]
Got it - merging then!

**Pull request merged**
